# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K2lXatGLX5ospyGZR-D7InS1RKIDNlIP
"""

import pandas as pd
import random
import datetime as dt

# Listas base realistas para Calzados Dayana
nombres = [
    "Valeria Mendoza","Carolina Huamán","Andrea Torres","Diana Rojas","Sofía Paredes",
    "Lucía Cárdenas","Daniela Chávez","Alejandra Flores","María López","Julieta Ibáñez",
    "Paula Quispe","Ariana Salazar","Fiorella Vega","Nicole Gutiérrez","Valentina Ramos",
    "Camila Arce","Bianca Morales","Mónica Sandoval","Karla Guevara","Melissa Navarro",
    "Rocío Poma","Zulema Prado","Adriana Pizarro","Patricia Rivas","Nathaly Oré",
    "Yuliana Cueva","Génesis Campos","Cinthya Soto","Mariela Castro","Carmen Zevallos",
    "Milagros Rengifo","Fátima Díaz","Ruth Tantalean","Angie Farfán","Alison Cuadros",
    "Briana Aguilar","Estefanía Núñez","Brenda Uceda","Liliana Huerta","Sandra Casas"
]

fuentes = ["Instagram","Facebook","Google","TikTok","Referido","Web orgánico"]

productos = [
    "Sandalia Fiorella","Tacón Viena Elegance","Sandalia Roma Casual",
    "Plataforma Milano","Bota Siena Fashion","Bailarina Suede"
]

categorias = {
    "Sandalia Fiorella": "Plataforma",
    "Tacón Viena Elegance": "Tacones",
    "Sandalia Roma Casual": "Casual",
    "Plataforma Milano": "Plataforma",
    "Bota Siena Fashion": "Casual",
    "Bailarina Suede": "Bailarinas"
}

clusters = ["Verano Chic","Boda & Fiesta","Casual Office","Urbano Trendy","Street Style"]
estados = ["Sin añadir","Añadió","Abandonó carrito","Compró"]
dispositivos = ["Móvil","Desktop"]
ubicaciones = [
    "Lima - Los Olivos","Lima - Surco","Lima - SJL","Callao","Arequipa","Cusco",
    "Piura","Ica","La Libertad","Junín","Lambayeque","Lima - Pueblo Libre","Lima - San Borja"
]

data = []
hoy = dt.date.today()

for i in range(1, 101):  # 100 leads
    nombre = random.choice(nombres)
    producto = random.choice(productos)
    categoria = categorias[producto]
    fuente = random.choice(fuentes)
    interacciones = random.randint(1, 22)

    # Probabilidad más alta si interactuó más
    base_prob = 0.2 + (interacciones / 30)
    probabilidad = min(round(base_prob + random.uniform(-0.15, 0.25), 2), 0.98)
    probabilidad = max(probabilidad, 0.05)

    # Ticket esperado depende de probabilidad
    if probabilidad > 0.75:
        ticket = round(random.uniform(159.90, 259.90), 2)
    elif probabilidad > 0.5:
        ticket = round(random.uniform(99.90, 189.90), 2)
    else:
        ticket = round(random.uniform(59.90, 129.90), 2)

    # Estado de carrito según probabilidad
    if probabilidad > 0.8:
        estado = random.choice(["Compró","Abandonó carrito"])
    elif probabilidad > 0.55:
        estado = random.choice(["Añadió","Abandonó carrito"])
    else:
        estado = random.choice(["Sin añadir","Añadió"])

    dias_atras = random.randint(1, 45)
    ultima_visita = (hoy - dt.timedelta(days=dias_atras)).isoformat()

    fila = {
        "id": i,
        "nombre_completo": nombre,
        "fuente": fuente,
        "producto_visto": producto,
        "categoria": categoria,
        "talla": random.randint(35, 40),
        "interacciones": interacciones,
        "cluster": random.choice(clusters),
        "probabilidad_compra": probabilidad,
        "ticket_esperado": ticket,
        "ultima_visita": ultima_visita,
        "estado_carrito": estado,
        "dispositivo": random.choice(dispositivos),
        "comentarios": "",
        "ubicacion": random.choice(ubicaciones)
    }
    data.append(fila)

df = pd.DataFrame(data)
df.head()
# Clasificación de leads según probabilidad de compra
def clasificar(prob):
    if prob >= 0.75:
        return "Alta prioridad"
    elif prob >= 0.45:
        return "Media prioridad"
    else:
        return "Baja prioridad"

df["prioridad"] = df["probabilidad_compra"].apply(clasificar)

df[["nombre_completo","producto_visto","probabilidad_compra","prioridad"]].head(10)

def recomendacion_IA(prioridad):
    if prioridad == "Alta prioridad":
        return "Enviar cupón + mensaje personalizado por WhatsApp para cerrar venta."
    elif prioridad == "Media prioridad":
        return "Mandar catálogo digital y mostrar reseñas de clientas para aumentar interés."
    else:
        return "Reorientar anuncios en Instagram/TikTok con productos tendencia."

df["recomendacion_IA"] = df["prioridad"].apply(recomendacion_IA)

df[["nombre_completo","prioridad","recomendacion_IA"]].head(10)

!pip install streamlit

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# 
# st.title("Clasificador de Leads – Calzados Dayana 👠")
# 
# uploaded_file = st.file_uploader("Sube tu archivo CSV", type=["csv"])
# 
# if uploaded_file is not None:
#     df = pd.read_csv(uploaded_file)
# 
#     # Clasificar prioridad
#     def clasificar(prob):
#         if prob >= 0.75:
#             return "Alta prioridad"
#         elif prob >= 0.45:
#             return "Media prioridad"
#         else:
#             return "Baja prioridad"
# 
#     df["prioridad"] = df["probabilidad_compra"].apply(clasificar)
# 
#     # IA generativa de recomendaciones
#     def recomendacion(prioridad):
#         if prioridad == "Alta prioridad":
#             return "Enviar cupón + WhatsApp para cerrar venta."
#         elif prioridad == "Media prioridad":
#             return "Mandar catálogo + reseñas de clientas."
#         else:
#             return "Reorientar anuncios en Instagram/TikTok."
# 
#     df["recomendacion_IA"] = df["prioridad"].apply(recomendacion)
# 
#     st.subheader("Resultados")
#     st.dataframe(df[["nombre_completo","prioridad","recomendacion_IA"]])
#

!streamlit run app.py &